project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cities/", include("weathers.urls")),
    path('', home, name="home"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weathers/urls.py
from django.urls import path

from . import views

app_name = 'weathers'

urlpatterns = [
    path("", views.index, name="cities"),
    path("<int:pk>", views.detail, name="city"),
    path("add", views.add_city, name="city_add"),
]

weathers/models.py
from django.db import models


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


COUNTRY_CHOICES = {
    "LT": "Lietuva",
    "LV": "Latvija",
    "EST": "Estija",
}


class City(BaseModel):
    name = models.CharField(max_length=50, default='', blank=True, unique=True)
    country = models.CharField(default='Lietuva', max_length=100, choices=COUNTRY_CHOICES)
    coordination_x = models.FloatField(default=0)
    coordination_y = models.FloatField(default=0)

    def __str__(self):
        return f'{self.name} in {self.country}, coordination: {self.coordination_x, self.coordination_y}'


class CityWeathers(BaseModel):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    temperature = models.FloatField(default=0)
    time_stamp = models.DateTimeField(auto_now=True)

weathers/forms.py
from django import forms


class NameForm(forms.Form):
    city = forms.CharField(max_length=20, min_length=3)
    country = forms.CharField(max_length=50, min_length=3)
    coordination_x = forms.FloatField(min_value=0, max_value=120)
    coordination_y = forms.FloatField(min_value=0, max_value=120)

project/views.py
from django.shortcuts import render


def home(request):
    context = {}
    return render(request=request, template_name="home.html", context=context)

weathers/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .helper_functions.weathers import get_temperature
from .models import City, CityWeathers
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .forms import NameForm


def index(request):
    cities = City.objects.all()
    context = {'cities': cities}
    return render(request=request, template_name="weathers/cities.html", context=context)


def detail(request, pk):
    city = None
    try:
        city = City.objects.get(pk=pk)
    except City.DoesNotExist:
        pass

    context = {
        'city': city,
        'value': str(pk) * 5,
        'cities': City.objects.all(),
        'temperature': get_temperature(10, 10),
    }

    city_weathers = CityWeathers.objects.create(city=city, temperature=15)
    city_weathers.save()

    return render(request=request, template_name="weathers/city.html", context=context)


def add_city(request):
    if request.method == "POST":
        form = NameForm(request.POST)
        if form.is_valid():
            city = City.objects.create(
                name=form.cleaned_data["city"],
                country=form.cleaned_data["country"],
                coordination_x=form.cleaned_data["coordination_x"],
                coordination_y=form.cleaned_data["coordination_y"],
            )
            city.save()
            return HttpResponseRedirect(reverse("weathers:cities"))
    else:
        form = NameForm()
    context = {"form": form}
    return render(request=request, template_name="weathers/city_add_1.html", context=context)


"""
def add_city(request):
    if request.method == "POST":
        city = City.objects.create(
            name=request.POST["city"],
            country=request.POST["country"],
            coordination_x=request.POST["coordination_x"],
            coordination_y=request.POST["coordination_y"],
        )
        city.save()
        return HttpResponseRedirect(reverse("weathers:cities", args=[10]))
    context = {}
    return render(request=request, template_name="weathers/city_add.html", context=context)
"""

templates/home.html
{% extends 'main.html' %}

{% block content %}

    <h6> Mes turime home page </h6>

{% endblock %}

templates/main.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <header>
    {% include 'navbar.html' %}
  </header>
  <body>
    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}" >Home</a>
        </li>
        <li class="nav-item">
           <a class="nav-link active" aria-current="page" href="{% url 'weathers:cities' %}" > Cities </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

weathers/templates/weathers/cities.html
{% extends 'main.html' %}

{% block content %}

    {% if cities %}
        <ul>
        {% for city in cities %}
            <li><a href="{% url 'weathers:city' city.id %}" >{{ city.name }} {{ city.country }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No cities are available.</p>
    {% endif %}

    <a href="{% url 'weathers:city_add' %}" > <button type="button" class="btn btn-primary" > Add city </button> </a>

{% endblock %}

weathers/templates/weathers/city.html
{% extends 'main.html' %}

{% block content %}

    {% if city %}

        {{ city.name }}
        {{ city.country }}
        {{ value }}
        2.8
    {% else %}
        <ul>
            {{ value }}
            {% for city in cities %}
                <p> mes esame cia </p>
                <li><a href="{% url 'weathers:city' city.id %}" >{{ city.name }} {{ city.country }} </a></li>
            {% endfor %}
            {% for weather in weathers %}
                <p> {{ weather.city. }} </p>
                <li><a href="{% url 'weathers:city' city.id %}" >{{ city.name }} {{ city.country }} </a></li>
            {% endfor %}
        </ul>
    {% endif %}

{% endblock %}

weathers/templates/weathers/city_add.html
{% extends 'main.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}
            <label for="city"> City: </label>
            <input id="city" type="text" name="city">

            <label for="country"> Country: </label>
            <input id="country" type="text" name="country">

            <label for="coordination_x"> Coordination_X: </label>
            <input id="coordination_x" type="number" name="coordination_x">

            <label for="coordination_y"> Coordination_Y: </label>
            <input id="coordination_y" type="number" name="coordination_y">

        <input type="submit" value="Add">
    </form>

{% endblock %}

weathers/templates/weathers/city_add_1.html
{% extends 'main.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}